lab_1/urls.py
from django.contrib import admin
# from django.urls import include, path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^profile/', include('lab_1_profile.urls', namespace="profile")),
    url(r'^', include('lab_3.urls', namespace="welcome")),
    url(r'^matakuliah/', include('lab_5.urls', namespace="table")),
    url(r'^daftar-kegiatan/', include('lab_6.urls', namespace="daftar-kegiatan")),
    url(r'^accordion/', include('lab_7.urls', namespace="accordion")),
    url(r'^daftar-buku/', include('lab_8.urls', namespace="daftarBuku")),
    url(r'^account/', include('lab_9.urls', namespace="account")),
    url(r'^admin/', admin.site.urls),
]

lab_1_profile/urls.py
from django.urls import path

from . import views

app_name = 'lab_1_profile'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_3/urls.py
from django.urls import path

from . import views

app_name = "lab_3"

urlpatterns = [
    path('', views.index, name='index'),
    path('more/', views.more, name='more')
]

lab_5/urls.py
from django.urls import path

from . import views

app_name = "lab_5"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.matkul_create_form, name='create'),
    path('delete/<str:id>/', views.matkul_delete_form, name='delete'),
    path('detail/<str:id>/', views.matkul_specific_id, name='detail')
]

lab_6/urls.py
from django.urls import path

from . import views

app_name = "lab_6"

urlpatterns = [
    path('', views.index, name='index'),
    path('create-kegiatan/', views.create_kegiatan, name='create-kegiatan'),
    path('create-attendee/<str:id>/',
         views.create_attendee, name='create-attendee')

]

lab_7/urls.py
from django.urls import path

from . import views

app_name = "lab_7"

urlpatterns = [
    path('', views.index, name='index')
]

lab_8/urls.py
from django.urls import path

from . import views

app_name = "lab_8"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search1')
]

lab_9/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = "lab_9"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerViews, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

lab_3/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.


class Matkul (models.Model):
    nama = models.CharField(max_length=50, null=True)
    dosen = models.CharField(max_length=50, null=True)
    sks = models.IntegerField(null=True)
    deskripsi = models.TextField(max_length=500, null=True)
    semester = models.TextField(max_length=100, null=True)
    ruang = models.CharField(max_length=50, null=True)

lab_6/models.py
from django.db import models

# Create your models here.


class Person (models.Model):
    nama = models.CharField(max_length=50, null=True)
    domisili = models.CharField(max_length=50, null=True)


class Kegiatan (models.Model):
    nama = models.CharField(max_length=50, null=True)
    deskripsi = models.TextField(max_length=500, null=True)
    waktu = models.CharField(max_length=50, null=True)
    persons = models.ManyToManyField(Person, blank=True)

lab_7/models.py
from django.db import models

# Create your models here.

lab_8/models.py
from django.db import models

# Create your models here.

lab_5/forms.py
from django import forms
from .models import Matkul


class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = {
            'dosen',
            'sks',
            'deskripsi',
            'ruang',
            'nama',
            'semester'
        }

lab_6/forms.py
from django import forms
from .models import Kegiatan, Person


class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = {
            'nama',
            'deskripsi',
            'waktu',
            'persons'
        }


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = {
            'nama',
            'domisili'
        }

lab_3/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'welcome/welcome.html')


def more(request):
    return render(request, 'profile-more/profile-more.html')

lab_5/views.py
from django.shortcuts import render
from lab_5.models import Matkul
from lab_5.forms import MatkulForm
from django.shortcuts import redirect
# Create your views here.


def index(request):
    data = {}
    matkuls = Matkul.objects.all()
    data['datas'] = matkuls

    return render(request, 'table/table.html', data)


def matkul_create_form(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = MatkulForm()

    context = {
        'form': form
    }
    return render(request, 'form/form.html', context)


def matkul_delete_form(request, id):
    data = Matkul.objects.get(id=id)
    if request.method == "POST":
        data.delete()
        return redirect('lab_5:index')


def matkul_specific_id(request, id):
    data = Matkul.objects.get(id=id)
    context = {
        'data': data
    }
    return render(request, 'detail/detail.html', context)

lab_6/views.py
from django.shortcuts import render
from lab_6.models import Kegiatan, Person
from lab_6.forms import KegiatanForm, PersonForm
from django.shortcuts import redirect

# Create your views here.


def index(request):
    kegiatans = Kegiatan.objects.all()
    context = {
        'kegiatan': kegiatans
    }
    return render(request, 'kegiatan/kegiatan.html', context)


def create_kegiatan(request):
    form = KegiatanForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = KegiatanForm()

    context = {
        'form': form
    }
    return render(request, 'form_kegiatan/form_kegiatan.html', context)


def create_attendee(request, id):
    data = Kegiatan.objects.filter(id=id)
    test = Kegiatan.objects.all()
    print(test.first().persons.all())
    form = PersonForm(request.POST or None)
    if form.is_valid():
        form.save()
        data.first().persons.add(Person.objects.last())
        return redirect('lab_6:index')

    context = {
        'form': form
    }
    return render(request, 'form_attendee/form_attendee.html', context)

lab_7/views.py
from django.shortcuts import render, redirect

# Create your views here.


def index(request):
    return render(request, 'accordion/accordion.html')

lab_8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views here.


def index(request):
    data = requests.get(
        'https://www.googleapis.com/books/v1/volumes?q=Norwegianwood')
    data = data.json()
    data = data['items']
    context = {
        'data': data
    }
    return render(request, 'daftarBuku/daftarBuku.html', context)


def search(request):
    if request.POST.get('post_note', None) is not None:
        post_note = request.POST['post_note']
        url = "https://www.googleapis.com/books/v1/volumes?q=" + post_note
        data = requests.get(url)
        data = data.json()
        data = data['items']
        context = {
            'data': data
        }
    return JsonResponse(context, safe=False)

lab_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def index(request):
    return render(request, 'welcoming/welcoming.html')


def registerViews(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect('lab_9:login')
    else:
        form = UserCreationForm()
    return render(request, 'register/register.html', {'form': form})


def loginViews(request):
    return render(request, 'login/login.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=PT+Serif&display=swap"
      rel="stylesheet"
    />

    <!-- Optional theme -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
      integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
      crossorigin="anonymous"
    />

    {% block styling %} {% endblock %}

    <style>
      .burger {
        display: none;
        font-size: 28px;
      }

      #myLinks {
        display: none;
      }

      .burger a {
        color: white;
        padding: 14px 16px;
        text-decoration: none;
        display: block;
      }

      @media only screen and (max-width: 1000px) {
        #containerNav {
          display: none;
        }
        .burger {
          display: block;
        }

        nav {
          z-index: 10;
        }
      }
    </style>
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav
      class="navbar navbar-expand-lg navbar-light"
      style="margin: 0; background-color: #0f9d58"
    >
      <div
        id="containerNav"
        class="container"
        style="font-family: 'PT Serif', normal"
      >
        <div>
          <a
            href="{% url 'lab_3:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Welcome Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_1_profile:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Profile Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_3:more'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Experience Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_5:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Mata Kuliah</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_6:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Kegiatan</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_7:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Accordion</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_8:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Daftar Buku</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_9:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Logout</a
          >
        </div>
      </div>
      <div class="burger">
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
        </a>
        <div id="myLinks">
          <div>
            <a
              href="{% url 'lab_3:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Welcome Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_1_profile:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Profile Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_3:more'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Experience Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_5:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Mata Kuliah</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_6:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Kegiatan</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_7:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Accordion</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_8:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Daftar Buku</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_9:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Logout</a
            >
          </div>
        </div>
      </div>
    </nav>
    {% else %}
    <nav
      class="navbar navbar-expand-lg navbar-light"
      style="margin: 0; background-color: #0f9d58"
    >
      <div
        id="containerNav"
        class="container"
        style="font-family: 'PT Serif', normal"
      >
        <div>
          <a
            href="{% url 'lab_3:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Welcome Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_1_profile:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Profile Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_3:more'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Experience Page</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_5:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Mata Kuliah</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_6:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Kegiatan</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_7:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Accordion</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_8:index'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Daftar Buku</a
          >
        </div>
        <div>
          <a
            href="{% url 'lab_9:login'%}"
            style="color: white; font-size: 20px; font-weight: 700"
            >Login</a
          >
        </div>
      </div>
      <div class="burger">
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
        </a>
        <div id="myLinks">
          <div>
            <a
              href="{% url 'lab_3:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Welcome Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_1_profile:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Profile Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_3:more'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Experience Page</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_5:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Mata Kuliah</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_6:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Kegiatan</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_7:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Accordion</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_8:index'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Daftar Buku</a
            >
          </div>
          <div>
            <a
              href="{% url 'lab_9:login'%}"
              style="color: white; font-size: 20px; font-weight: 700"
              >Login</a
            >
          </div>
        </div>
      </div>
    </nav>
    {% endif %} {% block content %} {% endblock %}

    <script>
      function myFunction() {
        var x = document.getElementById("myLinks");
        if (x.style.display === "block") {
          x.style.display = "none";
        } else {
          x.style.display = "block";
        }
      }
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"
    ></script>

    {% block javascript %} {% endblock %}
  </body>
</html>