lab_1/urls.py
from django.contrib import admin
# from django.urls import include, path
from django.conf.urls import url, include

urlpatterns = [
    url(r'^profile/', include('lab_1_profile.urls', namespace="profile")),
    url(r'^', include('lab_3.urls', namespace="welcome")),
    url(r'^matakuliah/', include('lab_5.urls', namespace="table")),
    url(r'^daftar-kegiatan/', include('lab_6.urls', namespace="daftar-kegiatan")),
    url(r'^accordion/', include('lab_7.urls', namespace="accordion")),
    url(r'^daftar-buku/', include('lab_8.urls', namespace="daftarBuku")),
    url(r'^account/', include('lab_9.urls', namespace="account")),
    url(r'^admin/', admin.site.urls),
]

lab_1_profile/urls.py
from django.urls import path

from . import views

app_name = 'lab_1_profile'

urlpatterns = [
    path('', views.index, name='index'),
]

lab_3/urls.py
from django.urls import path

from . import views

app_name = "lab_3"

urlpatterns = [
    path('', views.index, name='index'),
    path('more/', views.more, name='more')
]

lab_5/urls.py
from django.urls import path

from . import views

app_name = "lab_5"

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.matkul_create_form, name='create'),
    path('delete/<str:id>/', views.matkul_delete_form, name='delete'),
    path('detail/<str:id>/', views.matkul_specific_id, name='detail')
]

lab_6/urls.py
from django.urls import path

from . import views

app_name = "lab_6"

urlpatterns = [
    path('', views.index, name='index'),
    path('create-kegiatan/', views.create_kegiatan, name='create-kegiatan'),
    path('create-attendee/<str:id>/',
         views.create_attendee, name='create-attendee')

]

lab_7/urls.py
from django.urls import path

from . import views

app_name = "lab_7"

urlpatterns = [
    path('', views.index, name='index')
]

lab_8/urls.py
from django.urls import path

from . import views

app_name = "lab_8"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name='search1')
]

lab_9/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


app_name = "lab_9"

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.registerViews, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

lab_1_profile/models.py
from django.db import models

# Create your models here.

lab_3/models.py
from django.db import models

# Create your models here.

lab_5/models.py
from django.db import models

# Create your models here.


class Matkul (models.Model):
    nama = models.CharField(max_length=50, null=True)
    dosen = models.CharField(max_length=50, null=True)
    sks = models.IntegerField(null=True)
    deskripsi = models.TextField(max_length=500, null=True)
    semester = models.TextField(max_length=100, null=True)
    ruang = models.CharField(max_length=50, null=True)

lab_6/models.py
from django.db import models

# Create your models here.


class Person (models.Model):
    nama = models.CharField(max_length=50, null=True)
    domisili = models.CharField(max_length=50, null=True)


class Kegiatan (models.Model):
    nama = models.CharField(max_length=50, null=True)
    deskripsi = models.TextField(max_length=500, null=True)
    waktu = models.CharField(max_length=50, null=True)
    persons = models.ManyToManyField(Person, blank=True)

lab_7/models.py
from django.db import models

# Create your models here.

lab_8/models.py
from django.db import models

# Create your models here.

lab_9/models.py
from django.db import models

# Create your models here.

lab_5/forms.py
from django import forms
from .models import Matkul


class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = {
            'dosen',
            'sks',
            'deskripsi',
            'ruang',
            'nama',
            'semester'
        }

lab_6/forms.py
from django import forms
from .models import Kegiatan, Person


class KegiatanForm(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = {
            'nama',
            'deskripsi',
            'waktu',
            'persons'
        }


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = {
            'nama',
            'domisili'
        }

lab_1_profile/views.py
from django.shortcuts import render


def index(request):
    content = {
        'nama': 'Sukma Firdaus',
        'npm': '1606875831',
        'angkatan': '2016',
        'kampus': 'Universitas Indonesia',
        'hobi': 'Santai',
        'deskripsi': 'Mahasiswa Ilmu Komputer angkatan 2016, yang sedang mempelajari dunia "per-website-an"'
    }
    return render(request, 'profile/profile.html', content)

lab_3/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'welcome/welcome.html')


def more(request):
    return render(request, 'profile-more/profile-more.html')

lab_5/views.py
from django.shortcuts import render
from lab_5.models import Matkul
from lab_5.forms import MatkulForm
from django.shortcuts import redirect
# Create your views here.


def index(request):
    data = {}
    matkuls = Matkul.objects.all()
    data['datas'] = matkuls

    return render(request, 'table/table.html', data)


def matkul_create_form(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = MatkulForm()

    context = {
        'form': form
    }
    return render(request, 'form/form.html', context)


def matkul_delete_form(request, id):
    data = Matkul.objects.get(id=id)
    if request.method == "POST":
        data.delete()
        return redirect('lab_5:index')


def matkul_specific_id(request, id):
    data = Matkul.objects.get(id=id)
    context = {
        'data': data
    }
    return render(request, 'detail/detail.html', context)

lab_6/views.py
from django.shortcuts import render
from lab_6.models import Kegiatan, Person
from lab_6.forms import KegiatanForm, PersonForm
from django.shortcuts import redirect

# Create your views here.


def index(request):
    kegiatans = Kegiatan.objects.all()
    context = {
        'kegiatan': kegiatans
    }
    return render(request, 'kegiatan/kegiatan.html', context)


def create_kegiatan(request):
    form = KegiatanForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = KegiatanForm()

    context = {
        'form': form
    }
    return render(request, 'form_kegiatan/form_kegiatan.html', context)


def create_attendee(request, id):
    data = Kegiatan.objects.filter(id=id)
    test = Kegiatan.objects.all()
    print(test.first().persons.all())
    form = PersonForm(request.POST or None)
    if form.is_valid():
        form.save()
        data.first().persons.add(Person.objects.last())
        return redirect('lab_6:index')

    context = {
        'form': form
    }
    return render(request, 'form_attendee/form_attendee.html', context)

lab_7/views.py
from django.shortcuts import render, redirect

# Create your views here.


def index(request):
    return render(request, 'accordion/accordion.html')

lab_8/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json
# Create your views here.


def index(request):
    data = requests.get(
        'https://www.googleapis.com/books/v1/volumes?q=Norwegianwood')
    data = data.json()
    data = data['items']
    context = {
        'data': data
    }
    return render(request, 'daftarBuku/daftarBuku.html', context)


def search(request):
    if request.POST.get('post_note', None) is not None:
        post_note = request.POST['post_note']
        url = "https://www.googleapis.com/books/v1/volumes?q=" + post_note
        data = requests.get(url)
        data = data.json()
        data = data['items']
        context = {
            'data': data
        }
    return JsonResponse(context, safe=False)

lab_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def index(request):
    return render(request, 'welcoming/welcoming.html')


def registerViews(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            return redirect('lab_9:login')
    else:
        form = UserCreationForm()
    return render(request, 'register/register.html', {'form': form})


def loginViews(request):
    return render(request, 'login/login.html')

lab_3/templates/profile-more/profile-more.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/profile-more.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="contentLeft">
    <div class="contentLeftWrapper">
      <p class="workExp">Work Experience</p>
      <div class="textWrapper1">
        <p class="topText">Software Engineer (Internship)</p>
        <p class="midText">PT. Limawira Wisesa</p>
        <p class="botText">07/2018 - 08/2018</p>
      </div>
      <div class="textWrapper">
        <p class="topText">UI/UX Designer Frontend Developer</p>
        <p class="midText">PPL Fasilkom UI</p>
        <p class="botText">2019 - 2019</p>
      </div>
      <div class="textWrapper">
        <p class="topText">Backend Developer (Internship)</p>
        <p class="midText">PT. Jojonomic Indonesia</p>
        <p class="botText">06/2019 – 08/2019</p>
      </div>
      <div class="textWrapper">
        <p class="topText">Fullstack Engineer (Internship)</p>
        <p class="midText">PT. Karpalabs Indonesia</p>
        <p class="botText">08/2020 – Present</p>
      </div>
      {% comment %}
      <div class="tombolBawahKiri">
        <a href="{% url 'lab_1_profile:index'%}">
          <i style="margin: 0; font-size: 50px" class="fa fa-arrow-left"></i>
          <p style="font-size: 17px; font-weight: 500">Welcoming</p>
        </a>
      </div>
      {% endcomment %}
    </div>
  </div>
  <div class="contentRight">
    <div class="contentRightWrapper">
      <p class="personalProj">Personal Project</p>
      <div class="textWrapper1">
        <p class="topText">Makan Apa Hari Ini (MAHI)</p>
        <p class="midText">
          A recommender system algorithm to decide what to eat on Fasilkom UI
        </p>
        <p class="botText">2018 - 2018</p>
      </div>
      <div class="textWrapper">
        <p class="topText">Kydos Official Website</p>
        <p class="midText">
          Making an official website for my own clothing brand Kydos.official.
          Developed with React JS during quarantine (not done yet)
        </p>
        <p class="botText">2020 - 2020</p>
      </div>
      <div class="contentSmile">
        <p>Thank you!</p>
      </div>
      {% comment %}
      <div id="resp" class="tombolBawahKiriResp">
        <a href="{% url 'lab_1_profile:index'%}">
          <i style="margin: 0; font-size: 50px" class="fa fa-arrow-left"></i>
          <p style="font-size: 17px; font-weight: 500">Welcoming</p>
        </a>
      </div>
      {% endcomment %}
    </div>
  </div>
</div>
{% endblock %}

lab_3/templates/welcome/welcome.html
{% extends 'base.html' %} 
{% load static %}

{% block styling %}
<link rel="stylesheet" href="{% static 'css/welcome.css' %}" />
{% endblock %}

{% block content %}

<div class="container-fluid">
  <div class="midContent">
    <div style="z-index: 5;" class="bigText">
      <p id="hey">Hey there!</p>
      <p id="come">Come see my profile</p>
    </div>
    <div>
      <a href='{% url 'lab_1_profile:index' %} '>
        <i class="fa fa-arrow-right" id="arrow"></i>
      </a>
    </div>
  </div>
</div>
{% endblock %}

lab_5/templates/form/form.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="all-content">
    <div style="width: 35vw; margin: auto">
      <h1>Form Penambahan Mata Kuliah</h1>
    </div>
    <form class="form-form" method="POST">
      {% csrf_token %}
      <div class="form">
        <div class="form-kiri">
          <div class="isi">
            <label>Mata Kuliah : </label>
            {{form.nama}}
          </div>
          <div class="isi">
            <label>Nama Dosen : </label>
            {{form.dosen}}
          </div>
          <div class="isi">
            <label>Jumlah SKS : </label>
            {{form.sks}}
          </div>
          <div class="isi">
            <label>Ruangan : </label>
            {{form.ruang}}
          </div>
        </div>
        <div class="form-kanan">
          <div class="isi">
            <label>Deskripsi Mata Kuliah : </label>
            {{form.deskripsi}}
          </div>
          <div class="isi">
            <label>Semester : </label>
            {{form.semester}}
          </div>
        </div>
      </div>
      <div style="float: right; margin-right: 20px">
        <input class="btn btn-outline-primary" type="submit" value="Save" />
      </div>
    </form>
  </div>
</div>
{% endblock %}

lab_6/templates/form_kegiatan/form_kegiatan.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/form_kegiatan.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="judul">
    <h1>Form Penambahan Kegiatan</h1>
  </div>
  <form method="POST">
    {% csrf_token %}
    <div class="form">
      <div class="isi">
        <label>Nama Kegiatan : </label>
        {{form.nama}}
      </div>
      <div class="isi">
        <label>Waktu Kegiatan : </label>
        {{form.waktu}}
      </div>
      <div class="isi">
        <label>Deskripsi Kegiatan : </label>
        {{form.deskripsi}}
      </div>
      <div style="float: right; margin-right: 20px">
        <input class="btn btn-primary" type="submit" value="Save" />
      </div>
    </div>
  </form>
</div>
{% endblock %}

lab_6/templates/kegiatan/kegiatan.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/kegiatan.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="judul">
    <h1>List Kegiatan</h1>
  </div>
  <div class="content">
    <div style="height: 30px">
      <div class="addKegiatan">
        <a
          href="{% url 'lab_6:create-kegiatan'%}"
          class="btn btn-primary"
          style="
            float: right;
            margin-bottom: 20px;
            width: 80px;
            height: 25px;
            font-weight: 700;
          "
        >
          <p>Add Kegiatan</p>
        </a>
      </div>
    </div>

    <div style="margin-top: 20px">
      {% if kegiatan %} {% for data in kegiatan %}
      <div style="margin-bottom: 35px" class="col-sm-4">
        <div class="card">
          <h5 class="card-title">{{data.nama}}</h5>
          <p id="waktu" class="card-text">{{data.waktu}}</p>
          <p
            style="color: black; margin: 0; font-weight: 700"
            class="card-text"
          >
            What are we going to do?
          </p>
          <p id="desc" class="card-text">{{data.deskripsi}}</p>
          <div class="card-body">
            <p
              style="font-weight: 700; color: black; margin-bottom: 0"
              class="card-text"
            >
              Attendees :
            </p>
            {% if data.persons.all %} {% for data in data.persons.all %}
            <div class="attendee">
              <p>{{data.nama}}</p>
              <p style="margin-left: 5px">( {{data.domisili}} )</p>
            </div>
            {% endfor %} {% else %} &nbsp; {%endif%}
          </div>

          <a
            href="{% url 'lab_6:create-attendee' data.id %}"
            id="iamin"
            class="btn btn-primary"
            >IAM IN!</a
          >
        </div>
      </div>
      {% endfor %} {% endif %}
    </div>
  </div>
</div>
{% endblock %}

lab_7/templates/accordion/accordion.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/accordion.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="judul">
    <h1>My Profile's Accordion</h1>
  </div>
  <div class="wrapper">
    <div id="div1" class="accordion">
      <div class="accordion_header">
        <div class="accordion_tab">Aktivitas</div>
        <div class="accordion_arrow">
          <button class="arrow_up">
            <i class="fa fa-arrow-up" aria-hidden="true"></i>
          </button>
          <button class="arrow_down">
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <div class="accordion_content">
        <div class="accordion_item">
          <!-- <p class="item_title">Accordion SubTitle</p> -->
          <p>
            Aktivitas saya saat ini (terutama di masa pandemi) yaitu
            bercengkrama dengan keluarga dirumah tentunya, selain itu juga
            sebisa mungkin mengikuti perkuliahan yang saya ambil di semester ini
            dengan baik (:
          </p>
        </div>
      </div>
    </div>
    <div id="div2" class="accordion">
      <div class="accordion_header">
        <div class="accordion_tab">Pengalaman Organisasi/Kepanitiaan</div>
        <div class="accordion_arrow">
          <button class="arrow_up">
            <i class="fa fa-arrow-up" aria-hidden="true"></i>
          </button>
          <button class="arrow_down">
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <div class="accordion_content">
        <div class="accordion_item">
          <!-- <p class="item_title">Accordion SubTitle</p> -->
          <p>-</p>
        </div>
      </div>
    </div>
    <div id="div3" class="accordion">
      <div class="accordion_header">
        <div class="accordion_tab">Prestasi</div>
        <div class="accordion_arrow">
          <button class="arrow_up">
            <i class="fa fa-arrow-up" aria-hidden="true"></i>
          </button>
          <button class="arrow_down">
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <div class="accordion_content">
        <div class="accordion_item">
          <!-- <p class="item_title">Accordion SubTitle</p> -->
          <p>Dapat mengerjakan lab PPW (:</p>
        </div>
      </div>
    </div>
    <div id="div4" class="accordion">
      <div class="accordion_header">
        <div class="accordion_tab">Motto</div>
        <div class="accordion_arrow">
          <button class="arrow_up">
            <i class="fa fa-arrow-up" aria-hidden="true"></i>
          </button>
          <button class="arrow_down">
            <i class="fa fa-arrow-down" aria-hidden="true"></i>
          </button>
        </div>
      </div>
      <div class="accordion_content">
        <div class="accordion_item">
          <!-- <p class="item_title">Accordion SubTitle</p> -->
          <p>
            In the end, people will judge you anyway. So don't live your life
            impressing others. Live your life impressing yourself.
            <br />
            <br />
            - Eunice Camacho Infante
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %} {% block javascript %}
<script>
  $(document).ready(function () {
    function firstAndLast(wrapper) {
      if (!wrapper) {
        return false;
      } else {
        wrapper.find("button:disabled").prop("disabled", false);
        wrapper.find("button.arrow_up:first").prop("disabled", true);
        wrapper.find("button.arrow_down:last").prop("disabled", true);
      }
    }

    firstAndLast($(".wrapper"));

    $(".accordion_tab").bind("click", function () {
      if ($(this).hasClass("active")) {
        $(".accordion_tab").each(function () {
          $(this).parent().parent().removeClass("active");
          $(this).removeClass("active");
        });
      } else {
        $(".accordion_tab").each(function () {
          $(this).parent().parent().removeClass("active");
          $(this).removeClass("active");
        });
        $(this).parent().parent().addClass("active");
        $(this).addClass("active");
      }
    });

    $("button").click(function (e) {
      e.preventDefault();
      var parent = $(this).closest(".accordion"),
        grandparent = $(this).closest(".wrapper");
      if ($(this).hasClass("arrow_up")) {
        parent.insertBefore(parent.prev(".accordion"));
        firstAndLast(grandparent);
      } else if ($(this).hasClass("arrow_down")) {
        parent.insertAfter(parent.next(".accordion"));
        firstAndLast(grandparent);
      }
    });
  });
</script>
{% endblock %}

lab_8/templates/daftarBuku/daftarBuku.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/daftarBuku.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="judul">
    <h1>Daftar Buku Favorit</h1>
    <div class="search">
      {% csrf_token %}
      <input
        name="search"
        id="search"
        type="text"
        placeholder="Search.."
        name="search"
      />
      <button type="submit" onclick="search()">
        <i class="fa fa-search"></i>
      </button>
    </div>
  </div>
  <div class="contentWrapper">
    <div class="row" style="width: 85vw; margin: auto; margin-top: 40px">
      {% for obj in data %}
      <div class="col-sm-2" style="margin-bottom: 20px">
        <div class="card h-100">
          <img
            class="card-img-top"
            src="{{obj.volumeInfo.imageLinks.thumbnail}}"
            alt="{{obj.volumeInfo.title}} pict"
            style="height: 180px"
          />
          <div class="card-body">
            <h5 class="card-title" style="text-align: left">
              {{obj.volumeInfo.title}} {{obj.volumeInfo.subtitle}}
            </h5>
            <p>
              Authors : {% for author in obj.volumeInfo.authors %} {{author}}
              {%endfor %}
            </p>
            <p>Description : {{obj.volumeInfo.description|truncatewords:15}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %} {% block javascript %}
<script>
  function search() {
    var asd = $("#search").val();
    var csrfToken = $("input[name='csrfmiddlewaretoken']");
    if (asd.length != 0) {
      $.ajax({
        url: "{% url 'lab_8:search1' %}",
        type: "POST",
        dataType: "json",
        data: { post_note: asd, csrfmiddlewaretoken: csrfToken.val() },
        cache: false,
        success: function (data) {
          $(".row").remove();
          $(".contentWrapper").append(
            '<div class="row" style="width: 85vw; margin: auto; margin-top: 40px"></div>'
          );
          $.each(data.data, function (key, val) {
            var ar = val.volumeInfo.authors;
            var temp = "";
            var desc = val.volumeInfo.description;
            if (desc != null) var desc = desc.slice(0, 70) + "...";
            if (ar != null) {
              for (var i = 0; i < ar.length; i++) {
                //temp += "<li>" + ar[i] + "</li>";
                temp = temp + val.volumeInfo.authors[i] + ", ";
              }
              temp = temp.slice(0, -1);
              temp = temp.slice(0, -1);
            }
            if (val.volumeInfo.subtitle != null) {
              if (val.volumeInfo.imageLinks != null) {
                if (desc != null) {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' src='" +
                      val.volumeInfo.imageLinks.thumbnail +
                      "' alt= '" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px'/><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      " " +
                      val.volumeInfo.subtitle +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p><p>Description : " +
                      desc +
                      "</p></div></div></div>"
                  );
                } else {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' src='" +
                      val.volumeInfo.imageLinks.thumbnail +
                      "' alt='" +
                      val.volumeInfo.title +
                      "' alt=" +
                      val.volumeInfo.title +
                      " style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p></div></div></div>"
                  );
                }
              } else {
                if (desc != null) {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' alt='" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p><p>Description : " +
                      desc +
                      "</p></div></div></div>"
                  );
                } else {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' alt='" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p></div></div></div>"
                  );
                }
              }
            } else {
              if (val.volumeInfo.imageLinks != null) {
                if (desc != null) {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' src='" +
                      val.volumeInfo.imageLinks.thumbnail +
                      "' alt= '" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px'/><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      " " +
                      val.volumeInfo.subtitle +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p><p>Description : " +
                      desc +
                      "</p></div></div></div>"
                  );
                } else {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' src='" +
                      val.volumeInfo.imageLinks.thumbnail +
                      "' alt='" +
                      val.volumeInfo.title +
                      "' alt=" +
                      val.volumeInfo.title +
                      " style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p></div></div></div>"
                  );
                }
              } else {
                if (desc != null) {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' alt='" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p><p>Description : " +
                      desc +
                      "</p></div></div></div>"
                  );
                } else {
                  $(".row").append(
                    "<div class='col-sm-2' style='margin-bottom: 20px'><div class='card h-100'><img class='card-img-top' alt='" +
                      val.volumeInfo.title +
                      "' style= 'height: 180px' /><div class='card-body'><h5 class='card-title' style='text-align: left'>" +
                      val.volumeInfo.title +
                      "</h5><p class='authors'>Authors : " +
                      temp +
                      "</p></div></div></div>"
                  );
                }
              }
            }
          });
        },
      });
    } else {
      alert("Tidak ada yang di cari!");
    }
  }
</script>
{% endblock %}

lab_9/templates/welcoming/welcoming.html
{% extends 'base.html' %} {% load static %} {% block styling %}
<link rel="stylesheet" href="{% static 'css/welcoming.css' %}" />
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="welcomingContent">
    <div class="textWrapper">
      <h1>Selamat datang, {{user.username}} 😊</h1>
    </div>
    <div class="logoutWrapper">
      <a class="btn btn-danger" href="{% url 'lab_9:logout' %}">Logout</a>
    </div>
  </div>
</div>
{% endblock %}